---

- name: Add dummy0 (Ubuntu/Debian)
  copy:
    dest: "/etc/network/interfaces.d/dummy0"
    content: |
      auto dummy0
      iface dummy0 inet manual
      bond-master {{ sp_bond.stdout }}
      mtu 9000
  when:
    - sp_bonding is defined and
      sp_bonding | bool
