---
- name: Deploy ifup-pre-local on CentOS/RHEL
  copy:
    src: ifup-pre-local
    dest: /sbin
    mode: 0755

- name: Add dummy0 on CentOS/RHEL
  copy:
    dest: "/etc/sysconfig/network-scripts/ifcfg-dummy0"
    content: |
      DEVICE=dummy0
      ONBOOT=yes
      TYPE=dummy
      MASTER={{ sp_bond.stdout }}
      SLAVE=yes
      BOOTPROTO=none
      MTU=9000
      NM_CONTROLLED=no
  when:
    - sp_bonding is defined and
      sp_bonding | bool