---
# handlers file for storpool_common
- name: Restart journald service
  systemd:
    name: systemd-journald
    state: restarted

- name: Gather OS package facts
  package_facts:
    manager: auto
