- name: "make some directories"
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "/etc/storpool"
    - "/etc/storpool.conf.d"
    - "/usr/lib/storpool"
    - "{{ sp_toolsdir }}"
