- name: "restart rsyslog"
  systemd:
    name: rsyslog
    state: restarted
    enabled: yes

- name: "reload sysctl entries"
  shell: '`which sysctl` --system'

- name: "increase crashkernel size on Ubuntu"
  shell: 'echo "GRUB_CMDLINE_LINUX_DEFAULT=\"\$GRUB_CMDLINE_LINUX_DEFAULT crashkernel=512M"\" > /etc/default/grub.d/kdump-tools.cfg'
  when: ansible_distribution == 'Ubuntu'

- name: "run patchkdumptools on Ubuntu"
  shell: '/usr/lib/storpool/patchkdumptools'
  when: ansible_distribution == 'Ubuntu'

- name: "update grub.cfg to reflect changes"
  shell: 'update-grub2'
  when: ansible_distribution == 'Ubuntu'
