- name: "adjust /etc/network/interfaces on Ubuntu/Debian (#1)"
  lineinfile:
    path: /etc/network/interfaces
    regexp: '^source /etc/network/interfaces.d'
    state: absent
  when: ansible_os_family == 'Debian'

- name: "adjust /etc/network/interfaces on Ubuntu/Debian (#2)"
  lineinfile:
    path: /etc/network/interfaces
    line: 'source-directory interfaces.d'
  when: ansible_os_family == 'Debian'

- name: "mkdir -p /etc/network/interfaces.d on Ubuntu/Debian"
  file:
    path: /etc/network/interfaces.d
    state: directory
    mode: '0755'
  when: ansible_os_family == 'Ubuntu'

- name: "generate StorPool net interfaces configuration"
  shell: "/usr/sbin/iface-genconf -a -o"

- name: "deploy ifup-pre-local on CentOS/RHEL"
  copy:
    src: ifup-pre-local
    dest: /sbin
    mode: 0755
  when: ansible_os_family == "RedHat"

- name: "deploy enslavedummy on Ubuntu/Debian"
  copy:
    src: enslavedummy
    dest: /sbin
    mode: 0755
  when: ansible_os_family == "Debian"

- name: "init iface1"
  shell: "/usr/sbin/storpool_showconf sp_iface1_cfg | cut -d: -f3 | xargs ifup"
  ignore_errors: yes

- name: "init iface2" 
  shell: "/usr/sbin/storpool_showconf sp_iface2_cfg | cut -d: -f3 | xargs ifup"
  ignore_errors: yes

- name: "init bond interfaces (if any)"
  shell: "/usr/sbin/storpool_showconf sp_iface1_cfg | cut -d: -f2 | cut -d. -f1 | xargs ifup"
  ignore_errors: yes

- name: "init iface1 VLANs (if any)"
  shell: "/usr/sbin/storpool_showconf sp_iface1_cfg | cut -d: -f2 | xargs ifup"
  ignore_errors: yes

- name: "init iface2 VLANs (if any)"
  shell: "/usr/sbin/storpool_showconf sp_iface2_cfg | cut -d: -f2 | xargs ifup"
  ignore_errors: yes
