- name: "adjust /etc/network/interfaces on Ubuntu/Debian (#1)"
  lineinfile:
    path: /etc/network/interfaces
    regexp: '^source /etc/network/interfaces.d'
    state: absent
  when: ansible_os_family == 'Debian'
  tags:
  - debian_adjust_interfaces

- name: "adjust /etc/network/interfaces on Ubuntu/Debian (#2)"
  lineinfile:
    path: /etc/network/interfaces
    line: 'source-directory interfaces.d'
  when: ansible_os_family == 'Debian'
  tags:
  - debian_adjust_interfaces

- name: "mkdir -p /etc/network/interfaces.d on Ubuntu/Debian"
  file:
    path: /etc/network/interfaces.d
    state: directory
    mode: '0755'
  when: ansible_os_family == 'Debian'
  tags:
  - debian_make_interfaces_d

- name: "deploy ifup-pre-local on CentOS/RHEL"
  copy:
    src: ifup-pre-local
    dest: /sbin
    mode: 0755
  when: ansible_os_family == "RedHat"
  tags:
  - rhel_deploy_ifup_pre_local

- name: "deploy enslavedummy on Ubuntu/Debian"
  copy:
    src: enslavedummy
    dest: /sbin
    mode: 0755
  when: ansible_os_family == "Debian"
  tags:
  - debian_deploy_enslavedummy

- name: "generate StorPool net interfaces configuration"
  command: "/usr/sbin/iface-genconf -a {{ '-o' if sp_overwrite_iface_conf else '' }}"
  changed_when: false
  tags:
  - generate_network_conf

- name: "init iface1"
  shell: >
    set -o pipefail && \
      /usr/sbin/storpool_showconf sp_iface1_cfg | cut -d: -f3 | xargs ifup
  changed_when: false
  ignore_errors: yes
  tags:
  - init_iface1

- name: "init iface2"
  shell: >
    set -o pipefail && \
      /usr/sbin/storpool_showconf sp_iface2_cfg | cut -d: -f3 | xargs ifup
  changed_when: false
  ignore_errors: yes
  tags:
  - init_iface2

- name: "init bond interfaces (if any)"
  shell: >
    set -o pipefail && \
      /usr/sbin/storpool_showconf sp_iface1_cfg | cut -d: -f2 | cut -d. -f1 | xargs ifup
  changed_when: false
  ignore_errors: yes
  tags:
  - init_bond_iface
  - init_iface1
  - init_iface2

- name: "init iface1 VLANs (if any)"
  shell: >
    set -o pipefail && \
      /usr/sbin/storpool_showconf sp_iface1_cfg | cut -d: -f2 | xargs ifup
  changed_when: false
  ignore_errors: yes
  tags:
  - init_iface1

- name: "init iface2 VLANs (if any)"
  shell: >
    set -o pipefail && \
      /usr/sbin/storpool_showconf sp_iface2_cfg | cut -d: -f2 | xargs ifup
  changed_when: false
  ignore_errors: yes
  tags:
  - init_iface2
