- name: "deploy ifup-pre-local on CentOS/RHEL"
  copy:
    src: ifup-pre-local
    dest: /sbin
    mode: 0755
  when: ansible_os_family == "RedHat"

- name: "deploy enslavedummy on Ubuntu/Debian"
  copy:
    src: enslavedummy
    dest: /sbin
    mode: 0755
  when: ansible_os_family == "Debian"

- name: "get StorPool interfaces"
  shell: '/usr/sbin/storpool_showconf sp_iface1_cfg sp_iface2_cfg | cut -d: -f2 | cut -d. -f1'
  register: sp_interfaces

- name: "check if StorPool uses bond interfaces"
  set_fact:
    sp_bonding: "{{ true if sp_interfaces.stdout_lines | select('match', 'bond') | list | count > 0 else false }}"

- name: "get StorPool bond interface"
  shell: '/usr/sbin/storpool_showconf sp_iface1_cfg | cut -d: -f2 | cut -d. -f1'
  register: sp_bond
  when: sp_bonding

- name: "add dummy0 on CentOS/RHEL"
  copy:
    dest: '/etc/sysconfig/network-scripts/ifcfg-dummy0'
    content: |
      DEVICE=dummy0
      ONBOOT=yes
      TYPE=dummy
      MASTER={{ sp_bond.stdout }}
      SLAVE=yes
      BOOTPROTO=none
      MTU=9000
      NM_CONTROLLED=no
  when: sp_bonding and ansible_os_family == "RedHat"

- name: "get {{ sp_bond.stdout }} slave interfaces"
  shell: '/usr/sbin/storpool_showconf sp_iface1_cfg sp_iface2_cfg | cut -d: -f3'
  register: sp_bond_slaves
  when: sp_bonding and ansible_os_family == "Debian"

- name: "add dummy0 on Ubuntu/Debian"
  copy:
    dest: '/etc/network/interfaces.d/dummy0'
    content: |
      auto dummy0
      iface dummy0 inet manual
      bond-master {{ sp_bond.stdout }}
      mtu 9000
  when: sp_bonding and ansible_os_family == "Debian"

- name: "add enslavedummy hook to slave interfaces on Ubuntu/Debian"
  lineinfile:
    path: "/etc/network/interfaces.d/{{ item }}"
    line: "pre-up /sbin/enslavedummy {{ sp_bond.stdout }} dummy0 || true"
    state: present
  when: sp_bonding and ansible_os_family == "Debian"
  with_items: "{{ sp_bond_slaves.stdout_lines }}"
