- name: "check if storpool cgroups already exist"
  stat:
    path: /etc/cgconfig.d/storpool.slice.conf
  register: sp_slice
  tags:
  - sp_slice

- name: "Cache sp_slice fact"
  set_fact:
    sp_slice: "{{ sp_slice }}"
    cacheable: true
  tags:
  - sp_slice

- name: "storpool_cg: add set_memsw=0 on Ubuntu"
  set_fact:
    sp_cg_ubuntu: "{{ 'SET_MEMSW=0' if ansible_distribution == 'Ubuntu' else '' }}"
    cacheable: true
  tags:
  - ubuntu_storpool_cg

- name: "generate cgroups if missing"
  command: "/usr/sbin/storpool_cg conf {{ sp_cg_conf_extra }} {{ sp_cg_ubuntu }}"
  changed_when: false
  when: not sp_slice.stat.exists
  tags:
  - generate_cgroups

- name: "start/enable cgconfig"
  systemd:
    name: cgconfig
    state: started
    enabled: yes
  register: sp_cgconfig
  tags:
  - start_cgconfig

- name: "Cache sp_cgconfig fact"
  set_fact:
    sp_cgconfig: "{{ sp_cgconfig }}"
    cacheable: true
  tags:
  - start_cgconfig

- name: "cgconfig was active and SP cgroups already exist - trying migration"
  command: "/usr/sbin/storpool_cg conf -E -M {{ sp_cg_conf_extra }}"
  changed_when: false
  when: sp_cgconfig.status.ActiveState == 'active' and sp_slice.stat.exists
  tags:
  - start_cgconfig

- name: "cgconfig was active and SP cgroups did not exist - restarting cgconfig"
  systemd:
    name: cgconfig
    state: restarted
    enabled: yes
  when: sp_cgconfig.status.ActiveState == 'active' and not sp_slice.stat.exists
  tags:
  - start_cgconfig

- name: "re-generate cgroups on Ubuntu with memsw enabled"
  command: /usr/sbin/storpool_cg conf "{{ sp_cg_conf_extra }}"
  changed_when: false
  when: ansible_distribution == 'Ubuntu'
  tags:
  - ubuntu_storpool_cg
