#!/usr/bin/env ansible-playbook
---
- name: Gather localhost's facts
  hosts: localhost
  gather_subset: 'min'
  tasks: []
  tags:
    - always

- name: Ensure Python is installed
  hosts: storpool
  connection: ssh
  gather_facts: false
  become: true
  roles:
    - ensure_python
  tags:
    - always

- name: Configuring hosts
  hosts: storpool
  roles:
    - storpool.bootstrap_node
    - storpool.install_sp_python
  tags:
    - bootstrap-hosts

- name: Installing StorPool components
  hosts: storpool
  roles:
    - install_storpool_components
  tags:
    - install-storpool-components

- name: Configuring Networking
  hosts: storpool
  roles:
    - configure_networking
  tags:
    - configure-networking

- name: Configure Drives
  hosts: storpool_server
  gather_facts: false
  roles:
    - initialize_disks
  tags:
    - initialize-disks

- name: Configure StorPool CGroups
  hosts: storpool
  gather_facts: false
  roles:
    - configure-cgroups
  tags:
    - configure-cgroups

- import_playbook: playbooks/7_setup-services.yml
- import_playbook: playbooks/8_tests.yml
- import_playbook: playbooks/9_sed.yml
