#!/usr/bin/env ansible-playbook
---
- import_playbook: playbooks/1_prepare.yml
- import_playbook: playbooks/2_setup-infra.yml
- import_playbook: playbooks/3_install-storpool.yml
- import_playbook: playbooks/4_setup-network.yml
- import_playbook: playbooks/5_setup-drives.yml
- import_playbook: playbooks/6_setup-cgroups.yml
- import_playbook: playbooks/7_setup-services.yml
- import_playbook: playbooks/common_reboot.yml
- import_playbook: playbooks/8_tests.yml
- import_playbook: playbooks/9_sed.yml
