---
- name: Check if storpool cgroups already exist
  stat:
    path: /etc/cgconfig.d/storpool.slice.conf
  register: sp_slice
  tags: ['configure-cgroups']

- name: Cache sp_slice fact
  set_fact:
    sp_slice: "{{ sp_slice }}"
    cacheable: true
  tags: ['configure-cgroups']

- name: Add set_memsw=0 on Ubuntu (storpool_cg)
  set_fact:
    sp_cg_ubuntu: SET_MEMSW=0
    cacheable: true
  when:
    - ansible_distribution == 'Ubuntu'
  tags: ['configure-cgroups']

- name: Generate cgroups if missing
  command: "/usr/sbin/storpool_cg conf {{ sp_cg_conf_extra|default() }} {{ sp_cg_ubuntu|default() }}"
  changed_when: false
  when:
    - sp_slice.stat.exists is defined and
      not sp_slice.stat.exists|bool
  tags: ['configure-cgroups']

- name: Start/enable cgconfig
  systemd:
    name: cgconfig
    state: started
    enabled: yes
  register: sp_cgconfig
  tags: ['configure-cgroups']

- name: Cache sp_cgconfig fact
  set_fact:
    sp_cgconfig: "{{ sp_cgconfig|default() }}"
    cacheable: true
  tags: ['configure-cgroups']

- name: Cgconfig was active and SP cgroups already exist - trying migration
  command: "/usr/sbin/storpool_cg conf -E -M {{ sp_cg_conf_extra|default() }}"
  changed_when: false
  ignore_errors: true
  when:
    - sp_cgconfig.status.ActiveState == 'active' and
      sp_slice.stat.exists
  tags: ['configure-cgroups']

- name: Cgconfig was active and SP cgroups did not exist - restarting cgconfig
  systemd:
    name: cgconfig
    state: restarted
    enabled: yes
  when:
    - sp_cgconfig.status.ActiveState == 'active' and
      not sp_slice.stat.exists
  tags: ['configure-cgroups']

- name: Re-generate cgroups on Ubuntu with memsw enabled
  command: "/usr/sbin/storpool_cg conf {{ sp_cg_conf_extra|default() }}"
  changed_when: false
  ignore_errors: true
  when:
    - ansible_distribution == 'Ubuntu'
  tags: ['configure-cgroups']
