---
sp_configure_network: false
sp_overwrite_iface_conf: false
sp_single_iface: false
sp_new_cluster: false
sp_update_system: true
sp_selinux: "disabled"
sp_summary_wait: true
sp_node_roles: "client"
sp_drive_erase: false
sp_diskid_offset: 0
# Defines if we should manage the rc.local on the targeted host
sp_rc_local: true
# If the storage capacity on this device is greater than or equal to this
# size (in GB), the installation process will continue.
# NOTE: For VMs the limit is disabled.
bootstrap_host_data_disk_min_size: "{{ sp_vm | ternary('0', '50') }}"
# Valid sp_node_roles values
sp_valid_roles:
  - client
  - server
  - server:1
  - server:2
  - server:3
  - server:4
  - server:5
  - server:6
  - server:7
  - nvme
  - mgmt
  - bridge
  - iscsi
# List of boolean variables for validation
sp_bool_vars:
  - sp_poli
  - sp_new_cluster
  - sp_update_system
  - sp_configure_network
  - sp_overwrite_iface_conf
  - sp_disable_nm
  - sp_disable_fw
  - sp_vm
  - sp_drive_erase
  - sp_summary_wait
# Systemd services
sp_services:
  helper:
    - storpool_hugepages
    - storpool_cgmove
    - storpool_kdump
    - storpool_abrtsync
  common:
    - storpool_beacon
    - storpool_stat
    - storpool_block
  server:
    - storpool_controller
  nvme:
    - storpool_nvmed
  mgmt:
    - storpool_mgmt
  bridge:
    - storpool_bridge
  iscsi:
    - storpool_iscsi
rc_local_commands:
  - "/usr/bin/cpupower set -b 0; # set energy/performance policy to performance"
  - '/usr/bin/cpupower frequency-set -g performance; # set cpufreq/pstate governor to "performance"'
# StorPool tools download URLs
sp_install_getpackage_url: "https://vault.storpool.com/getpackage.py"
sp_install_helper_url: "https://vault.storpool.com/install_modules_helper.py"
# StorPool tools executables
sp_getpackage: "{{ sp_toolsdir }}/getpackage.py"
sp_install_helper: "{{ sp_toolsdir }}/install_modules_helper.py"

epel_repo_url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
epel_repo_gpg_key_url: "/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
epel_repofile_path: "/etc/yum.repos.d/epel.repo"
cache_timeout: 600

sp_disable_nm: true
sp_disable_fw: true
sp_config: "{{ inventory_dir|default(ansible_env.PWD) }}/storpool.conf"
sp_release_file: "web"
sp_toolsdir: "/root/storpool"
sp_release: "19.01"
sp_fw_ports:
  - 81
  - 3749
  - 47567
sp_dirs:
  - "/etc/storpool"
  - "/etc/storpool.conf.d"
  - "/usr/lib/storpool"
  - "{{ sp_toolsdir }}"
