---
- name: Get node id
  command: "{{ sp_showconf }} -n SP_OURID"
  changed_when: false
  register: sp_node_id
  tags:
    - setup-drives

- name: Convert sp_drives to list
  set_fact:
    sp_drives: "{{ sp_drive_list | sort | map('regex_replace', '^(.*)', '/dev/\\1') | list }}"
  tags:
    - setup-drives

- name: Calculate diskid prefix
  set_fact:
    sp_node_id: "{{ sp_node_id }}"
    sp_diskid_prefix: "{{ sp_node_id.stdout | int - sp_diskid_offset | int }}"
    cacheable: true
  tags:
    - setup-drives

- name: Validate diskid prefix
  fail:
    msg: "Disk id prefix {{ sp_diskid_prefix }} is not in range (1..39)! Please adjust sp_diskid_offset"
  when:
    - sp_diskid_prefix|int < 1 or
      sp_diskid_prefix|int > 39
  tags:
    - setup-drives
