---
- name: Copy drives init tools
  copy:
    src: "perform_disktest.sh"
    dest: "{{ sp_toolsdir }}"
    mode: 0755

- name: Test the drives
  command: "{{ sp_perform_disk_test }} {{ sp_drives | join(' ') }}"
  changed_when: false
