- name: mkdir /etc/storpool
  file:
    path: /etc/storpool
    state: directory

- name: mkdir /etc/storpool.conf.d
  file:
    path: /etc/storpool.conf.d
    state: directory

- name: mkdir {{ sp_toolsdir }}
  file:
    path: "{{ sp_toolsdir }}"
    state: directory

- name: mkdir /usr/lib/storpool
  file:
    path: /usr/lib/storpool
    state: directory

- name: Install EPEL
  yum:
    name: epel-release
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Upgrade all packages on CentOS/RHEL
  yum:
    name: '*'
    state: latest
  when: sp_update_system is defined and sp_update_system and (ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux')

- name: Install StorPool dependencies for CentOS/RHEL
  yum:
    name: "{{ packages }}"
    enablerepo: epel
  vars:
    packages:
    - wget
    - dmidecode
    - kexec-tools
    - logrotate
    - mcelog
    - rsync
    - lz4
    - libcgroup-tools
    - tuned
    - lshw
    - pciutils
    - psmisc
    - numactl
    - cpupowerutils
    - hwloc
    - libcgroup-tools
    - nvme-cli
    - fio
    - perf
    - smartmontools
    - socat
    - man
    - vim-enhanced
    - tmux
    - screen
    - bash-completion
    - mc
    - perl
    - perl-core
    - tcpdump
    - strace
    - mtr
    - sysstat
    - lsof
    - git
    - patch
    - bc
    - chrony
    - lldpd
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Upgrade all packages to the latest version
  apt:
    upgrade: yes
    update_cache: yes
  when: sp_update_system is defined and sp_update_system and (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')

- name: Install StorPool dependencies for Ubuntu/Debian
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - wget
    - dmidecode
    - kexec-tools
    - logrotate
    - rsync
    - liblz4-tool
    - lshw
    - pciutils
    - psmisc
    - numactl
    - hwloc
    - nvme-cli
    - fio
    - smartmontools
    - socat
    - man
    - tmux
    - screen
    - bash-completion
    - mc
    - perl
    - tcpdump
    - strace
    - mtr
    - sysstat
    - lsof
    - cgroup-tools
    - git
    - patch
    - chrony
    - lldpd
    - vlan
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
