- name: Remove swapfile from /etc/fstab
  mount:
    name: swap
    fstype: swap
    state: absent

- name: Remove /swap.img from /etc/fstab on Ubuntu
  mount:
    path: none
    fstype: swap
    src: /swap.img
    state: absent
  when: ansible_distribution == 'Ubuntu'

- name: Disable swap
  command: swapoff -a

- name: Delete /swap.img if exists
  file:
    path: /swap.img
    state: absent
