- name: Remove swapfile from /etc/fstab
  mount:
    name: swap
    fstype: swap
    state: absent

- name: Remove swap on Ubuntu
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
  with_items:
    - 'swap.img.swap'
    - 'swap.target'
  when: ansible_distribution == 'Ubuntu'

- name: Disable swap
  command: swapoff -a
