- name: Disable irqbalance
  systemd:
    name: irqbalance
    enabled: no
    state: stopped
  ignore_errors: yes

- name: Tuned profile
  shell: tuned-adm profile throughput-performance
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Enable tuned
  systemd:
    name: tuned
    enabled: yes
    state: started
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Enable mcelog
  systemd:
    name: mcelog
    enabled: yes
    state: started
  ignore_errors: yes

- name: Enable lldpd
  systemd:
    name: lldpd
    enabled: yes
    state: started
  ignore_errors: yes

- name: Limit journald memory
  lineinfile:
    path: /etc/systemd/journald.conf
    regexp: RuntimeMaxUse=
    line: RuntimeMaxUse=64M
    insertbefore: RuntimeKeepFree
  register: sp_journald

- name: Reload journald
  systemd:
    name: systemd-journald
    state: restarted
  when: sp_journald.changed

- name: Disable firewalld
  systemd:
    name: firewalld
    enabled: no
    state: stopped
  when: sp_disable_fw is defined and sp_disable_fw and (ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux')

- name: Adjust firewalld to allow sp_api (81/tcp)
  firewalld:
    port: 81/tcp
    permanent: yes
    immediate: yes
    state: enabled
  when: sp_disable_fw is not defined or not sp_disable_fw and (ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux')

- name: Adjust firewalld to allow sp_mgmt (47567/tcp)
  firewalld:
    port: 47567/tcp
    permanent: yes
    immediate: yes
    state: enabled
  when: sp_disable_fw is not defined or not sp_disable_fw and (ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux')

- name: Adjust firewalld to allow sp_bridge (3749/tcp)
  firewalld:
    port: 3749/tcp
    permanent: yes
    immediate: yes
    state: enabled
  when: sp_disable_fw is not defined or not sp_disable_fw and (ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux')

- name: Disable ufw
  systemd:
    name: ufw
    enabled: no
    state: stopped
  when: sp_disable_fw is defined and sp_disable_fw and ansible_distribution == 'Ubuntu'

- name: Adjust ufw to allow sp_api (81/tcp)
  ufw:
    rule: allow
    port: '81'
    proto: tcp
  when: (sp_disable_fw is not defined or not sp_disable_fw) and ansible_distribution == 'Ubuntu'

- name: Adjust ufw to allow sp_mgmt (47567/tcp)
  ufw:
    rule: allow
    port: '47567'
    proto: tcp
  when: (sp_disable_fw is not defined or not sp_disable_fw) and ansible_distribution == 'Ubuntu'

- name: Adjust ufw to allow sp_bridge (3749/tcp)
  ufw:
    rule: allow
    port: '3749'
    proto: tcp
  when: (sp_disable_fw is not defined or not sp_disable_fw) and ansible_distribution == 'Ubuntu'

- name: Disable NetworkManager
  systemd:
    name: NetworkManager
    enabled: no
    state: stopped
  when: sp_disable_nm is defined and sp_disable_nm and (ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux')

- name: update shmfs mount
  mount:
    name: /dev/shm
    src: none
    fstype: tmpfs
    opts: defaults,size=90%
    state: mounted
