- name: Generate build conf
  run_once: true
  become: no
  local_action: command chdir={{ sp_custdir }}/{{ customer }} /usr/local/bin/generate-build-conf 
  when: sp_release_file is not defined and customer is defined and sp_poli is defined and sp_poli

- name: Copy and unpack release via SP tools
  run_once: false
  become: no
  local_action: command chdir={{ sp_custdir }}/{{ customer }} /usr/local/bin/copytoservers r={{ sp_release }} host={{ inventory_hostname }}
  when: sp_release_file is not defined and customer is defined and sp_poli is defined and sp_poli

- name: Copy release
  copy:
    src: "{{ sp_releasefile }}"
    dest: "/root/storpool/"
  when: sp_release_file is defined

- name: Unpack release
  unarchive:
    src: "/root/storpool/{{ sp_releasefile }}"
    dest: /root/storpool/
    remote_src: yes
  when: sp_release_file is defined

- name: Detect the release version
  shell: 'ls -d ~/storpool/storpool-1[89].0*/ | sort -V | tail -n 1'
  register: sp_install_dir  

- name: set default services to install
  set_fact:
    sp_svc_install: "@block cli"

- name: decide on server
  set_fact:
    sp_svc_install: "{{ sp_svc_install }} server"
  when: sp_server is defined and sp_server

- name: decide on mgmt
  set_fact: 
    sp_svc_install: "{{ sp_svc_install }} mgmt"
  when: sp_mgmt is defined and sp_mgmt

- name: decide on bridge
  set_fact: 
    sp_svc_install: "{{ sp_svc_install }} bridge"
  when: sp_bridge is defined and sp_bridge

- name: decide on iscsi
  set_fact: 
    sp_svc_install: "{{ sp_svc_install }} iscsi"
  when: sp_iscsi is defined and sp_iscsi

- name: Install StorPool
  shell: "./install.sh {{ sp_svc_install }}"
  args:
    chdir: "{{ sp_install_dir.stdout }}"

- name: Check if EFI on RHEL/CentOS
  stat:
    path: /boot/efi/EFI/centos/grub.cfg
  register: sp_centos_efi
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Update GRUB for RHEL/CentOS
  shell: "/usr/sbin/grub2-mkconfig -o $(readlink -f /etc/grub2.cfg)"
  when: (ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux') and sp_centos_efi.stat.exists == False

- name: Update GRUB EFI for RHEL/CentOS
  shell: "/usr/sbin/grub2-mkconfig -o /boot/efi/EFI/centos/grub.cfg"
  when: (ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux') and sp_centos_efi.stat.exists == True

- name: Update GRUB for Debian-based distros
  shell: "update-grub2"
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

