- name: Make sure the node exists in storpool.conf
  shell: '[ -n "$(storpool_showconf -n -e SP_OURID)" ]'

- name: 'Adjust /etc/network/interfaces on Ubuntu (#1)'
  lineinfile:
    path: /etc/network/interfaces
    regexp: '^source /etc/network/interfaces.d'
    state: absent
  when: ansible_distribution == 'Ubuntu'

- name: 'Adjust /etc/network/interfaces on Ubuntu (#2)'
  lineinfile:
    path: /etc/network/interfaces
    line: 'source-directory interfaces.d'
  when: ansible_distribution == 'Ubuntu'

- name: Create /etc/network/interfaces.d if missing on Ubuntu/Debian
  file:
    path: /etc/network/interfaces.d
    state: directory
    mode: '0755'
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Generate network configuration
  shell: "/usr/sbin/iface-genconf -a -o"

- name: Install ifup-pre-local
  copy:
    src: ifup-pre-local
    dest: /sbin
    mode: 0755
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Install enslavedummy
  copy:
    src: enslavedummy
    dest: /sbin
    mode: 0755
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Start the first Storage interface 
  shell: "/usr/sbin/storpool_showconf sp_iface1_cfg | cut -d: -f3 | xargs ifup"
  ignore_errors: yes

- name: Start the second Storage interface 
  shell: "/usr/sbin/storpool_showconf sp_iface2_cfg | cut -d: -f3 | xargs ifup"
  ignore_errors: yes

- name: Start the bond (if any)
  shell: "/usr/sbin/storpool_showconf sp_iface1_cfg | cut -d: -f2 | cut -d. -f1 | xargs ifup"
  ignore_errors: yes

- name: Start VLAN on iface1 (if any)
  shell: "/usr/sbin/storpool_showconf sp_iface1_cfg | cut -d: -f2 | xargs ifup"
  ignore_errors: yes

- name: Start VLAN on iface2 (if any)
  shell: "/usr/sbin/storpool_showconf sp_iface2_cfg | cut -d: -f2 | xargs ifup"
  ignore_errors: yes
