
- name: Prepare cgroup override options
  set_fact:
    sp_cgconfig_extra: ""

- name: Decide on cores override
  when: sp_cores is defined
  set_fact:
    sp_cgconfig_extra: "{{ sp_cgconfig_extra }} CORES={{ sp_cores }}"

- name: Decide on hyperconverged override
  when: sp_hyperconverged is defined and sp_hyperconverged
  set_fact:
    sp_cgconfig_extra: "{{ sp_cgconfig_extra }} converged=1"

- name: Decide on system memory limit override
  when: sp_systerm_slice is defined
  set_fact:
    sp_cgconfig_extra: "{{ sp_cgconfig_extra }} system_limit={{ sp_system_slice }}"

- name: Generate cgroups
  shell: "/usr/sbin/storpool_cg conf {{ sp_cgconfig_extra }}"

- name: enable cgconfig
  systemd:
    name: cgconfig
    state: started
    enabled: yes

- name: Migrate cgroups
  shell: "/usr/sbin/storpool_cg conf -E -M {{ sp_cgconfig_extra }}"
  ignore_errors: yes
