- name: Adding sp_services variable if not defined
  ansible.builtin.set_fact:
    sp_services:
      - block
  when:
   - sp_services is undefined

- name: Making host part of storpool_block group
  ansible.builtin.add_host:
    name: "{{ item }}"
    groups:
      - storpool_block
  when:
    - sp_install_block_on_non_clients
    - '"block" not in sp_services'
  loop: "{{ groups['storpool'] }}"
  delegate_to: localhost

- name: Making host part of respective storpool_ groups
  ansible.builtin.add_host:
    name: "{{ item }}"
    groups: "{{ ['storpool'] | product(hostvars[item]['sp_services']) | map('join', '_') | list }}"
  loop: "{{ groups['storpool'] }}"
  delegate_to: localhost
