- name: Making host part of storpool_block group if it has no services defined
  ansible.builtin.add_host:
    name: "{{ item }}"
    groups:
      - storpool_block
  when:
    - sp_install_block_on_non_clients
    - sp_services | length == 0 or "block" not in sp_services
  loop: "{{ groups['storpool'] }}"
  delegate_to: localhost

- name: Making host part of respective storpool_ groups
  ansible.builtin.add_host:
    name: "{{ item }}"
    groups: "{{ ['storpool'] | product(sp_services) | map('join', '_') | list }}"
  loop: "{{ groups['storpool'] }}"
  delegate_to: localhost
