---
- name: Copy storpool.conf
  copy:
    src: "{{ sp_config }}"
    dest: /etc/
  tags:
    - copy-storpool-conf

- name: Create dirs
  include_tasks: "subtasks/create_directories.yml"

- name: Install support tools
  include_tasks: "subtasks/support_tools.yml"
  when:
    - sp_poli is defined and
      sp_poli | bool
  tags:
    - install_support_tools

- name: Test memory
  include_tasks: "subtasks/test_memory.yml"
  when:
    - sp_vm is defined and
      not sp_vm | bool
  tags:
    - test_memory
