galaxy_info:
  author: StorPool Operations
  description: Ansible role for StorPool installation
  company: StorPool
  license: Apache
  platforms:
    - name: CentOS
    - name: Debian
    - name: Ubuntu
  min_ansible_version: 2.7
  galaxy_tags: []
