---
- name: Disable UFW (Ubuntu/Debian)
  systemd:
    name: ufw
    enabled: false
    state: stopped
  ignore_errors: true
  when:
    - sp_disable_fw is defined and
      sp_disable_fw | bool
  tags: ['system-tune']

- name: Add StorPool ports to firewall - 81,3749,47567/TCP (Ubuntu/Debian)
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  ignore_errors: true
  with_items: "{{ sp_fw_ports }}"
  when:
    - sp_disable_fw is defined and
      not sp_disable_fw | bool
  tags: ['system-tune']

- name: Disable ondemand service (Ubuntu/Debian)
  systemd:
    name: ondemand
    enabled: false
    state: stopped
  ignore_errors: true
  when: ansible_distribution == 'Ubuntu'
  tags: ['system-tune']
