---
- name: Generate VF config
  command: /usr/lib/storpool/vf-genconf
  changed_when: false
  when:
    - sp_vm is defined and
      not sp_vm|bool
  tags: ['finalise']

- name: Get needed number of server instances
  script: get_instances.py
  args:
    executable: /opt/storpool/python3/bin/python3
  changed_when: false
  register: sp_instances
  when:
    - sp_roles is defined and
      sp_roles.server|bool
  tags: ['finalise']

- name: Run storpool_hugepages to apply NVME config
  command: /usr/sbin/storpool_hugepages
  changed_when: false
  when:
    - sp_roles is defined and
      sp_roles.nvme|bool
  tags: ['finalise']

- name: Add storpool_server instances to sp_systemd_services
  set_fact:
    sp_systemd_services: "{{ sp_systemd_services }} + {{ sp_instances.stdout_lines }}"
  when: sp_roles.server
  tags: ['finalise']

- name: Start/enable sp_systemd_services
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  changed_when: false
  with_items: "{{ sp_systemd_services }}"
  when:
    - start_services is not defined or
      start_services|bool
  tags: ['finalise']

- name: Populate service facts
  service_facts:
  tags: ['finalise']
