---
- reboot:
    msg: Reboot initiated by Ansible
    connect_timeout: 10
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
  when:
    - sp_reboot is defined and
      sp_reboot|bool
  tags: ['finalise', 'reboot']
