- name: Checking if raw interfaces are defined
  ansible.builtin.assert:
    that: sp_raw_interfaces is defined
    fail_msg: "Host doesn't have any raw interfaces configured"

- name: Creating a list of raw interfaces names
  ansible.builtin.set_fact:
    raw_interfaces_names: "{{ sp_raw_interfaces | split (' ') }}"

- name: Checking if atleast two interfaces are set
  ansible.builtin.assert:
    that: raw_interfaces_names | length >= 2
    fail_msg: "Not enough raw interfaces set, currently set {{ raw_interfaces_names | length }}"

- name: Checking if raw interface exists on the host
  ansible.builtin.assert:
    that: interface_name in ansible_interfaces
    fail_msg: "Interface {{ interface_name }} not found on host"
  loop: "{{ raw_interfaces_names }}"
  loop_control:
    loop_var: interface_name

- name: Checking if resolve network is defined
  ansible.builtin.assert:
    that: sp_network is defined
    fail_msg: "Resolve network is not configured"

- name: Configuring /etc/network/interfaces on Ubuntu 18.04
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/network/interfaces
    line: source-directory interfaces.d
    state: present

- name: Creating temporary configuration file
  ansible.builtin.tempfile:
    suffix: net_helper
  register: temporary_genconfig_parameters

- name: Execute net_helper genconfig with provided parameters
  ansible.builtin.shell: >-
    {{ net_helper_path }} genconfig
    {{ sp_raw_interfaces }}
    --sp-network {{ sp_network }}
    --sp-mode {{ sp_network_mode | quote }}
    {% if sp_vlan is defined and (sp_vlan | int) != 0 %}
    --vlan {{ sp_vlan }}
    {% endif %}
    {% if sp_mtu is defined %}
    --sp-mtu {{ sp_mtu }}
    {% endif %}
    {% if (sp_nm_controlled is defined and sp_nm_controlled | bool) or (ansible_os_family == 'RedHat' and (ansible_distribution_major_version | int) >= 8) %}
    --nm-controlled
    {% endif %}
    {% if disable_network_acceleration %}
    --no-hwacc
    {% endif %}
    {% if sp_bond_name is defined %}
    --sp-bond-name {{ sp_bond_name }}
    {% endif %}
    {% if sp_bridge_name is defined %}
    --sp-bridge-name {{ sp_bridge_name }}
    {% endif %}
    {% if sp_arp_ip_targets is defined %}
    --arp-ip-targets {{ sp_arp_ip_targets }}
    {% endif %}
    {% if sp_address_offset is defined %}
    --sp-address-offset {{ sp_address_offset }}
    {% endif %}
    {% if sp_addnet_address_offset is defined %}
    --sp-addnet-address-offset {{ sp_addnet_address_offset }}
    {% endif %}
    {% if add_iface_net is defined %}
    {% for net in add_iface_net %}
    --add-iface-net {{ net }}
    {% endfor %}
    {% endif %}
    {% if sp_iscsi_network_mode is defined %}
    --iscsi-mode {{ sp_iscsi_network_mode }}
    {% endif %}
    {% if iscsi_mtu is defined %}
    --iscsi-mtu {{ iscsi_mtu }}
    {% endif %}
    {% if iscsi_bond_name is defined %}
    --iscsi-bond-name {{ iscsi_bond_name }}
    {% endif %}
    {% if iscsi_bridge_name is defined %}
    --iscsi-bridge-name {{ iscsi_bridge_name }}
    {% endif %}
    {% if iscsi_arp_ip_targets is defined %}
    --iscsi-arp-ip-targets {{ iscsi_arp_ip_targets }}
    {% endif %}
    {% if sp_iscsi_address_offset is defined %}
    --sp-iscsi-address-offset {{ sp_iscsi_address_offset }}
    {% endif %}
    {% if iscsicfg_net is defined %}
    {% for iscsi_net in iscsicfg_net %}
    --iscsicfg-net {{ iscsi_net }}
    {% endfor %}
    {% endif %}
    > {{ temporary_genconfig_parameters.path }}
  register: genconfig_output
  changed_when: false

- name: Checking if net_helper configuration exists
  become: yes
  ansible.builtin.stat:
    path: "{{ genconfig_path }}"
  register: genconfig_file

- name: Checking if StorPool network interface configuration exists
  become: true
  ansible.builtin.stat:
    path: /etc/storpool.conf.d/net_helper.conf
  register: storpool_network_interface_configuration

- name: Generating diff output for current and new network configuration
  ansible.builtin.command: "/usr/bin/diff -u {{ genconfig_path }} {{ temporary_genconfig_parameters.path }}"
  register: network_configuration_diff
  failed_when: network_configuration_diff.rc == 2
  changed_when: false
  when:
    - genconfig_file.stat.exists

- name: Moving temporary network configuration to persistent
  become: yes
  ansible.builtin.copy:
    src: "{{ temporary_genconfig_parameters.path }}"
    dest: "{{ genconfig_path }}"
    remote_src: yes
  when:
    - not genconfig_file.stat.exists or (network_configuration_diff is defined and network_configuration_diff.rc == 1)

- name: Checking if interface configuration changes are required
  become: yes
  ansible.builtin.command: >-
    net_helper check --from-config {{ genconfig_path }} --exit-status 254
  register: interface_configuration_check
  changed_when:
    - interface_configuration_check.rc == 254
  failed_when:
    - interface_configuration_check.rc != 0
    - interface_configuration_check.rc != 254
  when:
    - storpool_network_interface_configuration.stat.exists

- name: Reconfiguring network
  block:
    - name: Gathering running services
      ansible.builtin.service_facts:
      when:
        - not force_network_reconfiguration

    - name: Checking if storpool services are running
      ansible.builtin.assert:
        that: "{{ services | selectattr('name', 'contains', 'storpool') | selectattr('state', 'eq', 'running') | length > 0 }}"
        fail_msg: "StorPool services are running, please stop them prior to changing network configuration"
      when:
        - not force_network_reconfiguration

    - name: Bringing down network interfaces
      become: yes
      ansible.builtin.command: net_helper up
      when:
        - force_network_reconfiguration

    - name: Cleaning up previous configuration
      become: yes
      ansible.builtin.command: >-
        net_helper cleanup
        {% if force_network_reconfiguration %}
        --stop-services
        {% endif %}
  when:
    - interface_configuration_check.changed

- name: Applying network configuration
  become: yes
  ansible.builtin.command: >-
    net_helper applyifcfg --from-config {{ genconfig_path }}
  when:
    - interface_configuration_check.changed

- name: Bringing up network interfaces
  become: yes
  ansible.builtin.command: net_helper up
  when:
    - sp_bring_up_network
    - interface_configuration_check.changed
