- name: Regathering network facts
  ansible.builtin.setup:
    gather_subset:
      - "!all"
      - "network"

- name: Retrieving configured interfaces from remote host
  become: yes
  ansible.builtin.shell: |
    export PATH=$PATH:/usr/sbin
    /usr/sbin/storpool_showconf -n -e -- SP_IFACE1_CFG SP_IFACE2_CFG
  register: all_interfaces_list
  failed_when: all_interfaces_list.rc != 0

- name: Checking if all interfaces exist
  ansible.builtin.assert:
    that: interface in ansible_interfaces
    fail_msg: "{{ interface }} not configured"
  loop_control:
    loop_var: interface_configuration
  loop: "all_interfaces_list.stdout_lines"

- name: Checking if all interfaces are up
  ansible.builtin.assert:
    that: hostvars[inventory_hostname]['ansible_' + interface]['active']
