---
- name: Get StorPool interfaces
  shell: >
    set -o pipefail && \
      /usr/sbin/storpool_showconf sp_iface1_cfg sp_iface2_cfg | cut -d: -f2 | cut -d. -f1
  changed_when: false
  register: sp_interfaces
  tags: ['setup-network']

- name: Check if StorPool uses bond interfaces
  set_fact:
    sp_bonding: "{{ true if sp_interfaces.stdout_lines | select('match', 'bond') | list | count > 0 else false }}"
  tags: ['setup-network']

- name: Get StorPool bond interface
  shell: >
    set -o pipefail && \
      /usr/sbin/storpool_showconf sp_iface1_cfg | cut -d: -f2 | cut -d. -f1
  changed_when: false
  register: sp_bond
  when: sp_bonding
  tags: ['setup-network']

- name: Include distro-specific tasks
  include_tasks: "subtasks/bond_adjustments_{{ ansible_os_family|lower }}.yml"
  tags: ['setup-network']
