---
- name: Install dependencies
  include_tasks: "dependencies.yml"

- name: Add/Update shmfs entry in fstab
  mount:
    name: /dev/shm
    src: none
    fstype: tmpfs
    opts: "size=90%,nosuid,nodev"
    state: mounted

- name: Disable swap
  command: swapoff -a
  changed_when: true
  when: ansible_swaptotal_mb > 0

- name: Remove swap from fstab
  lineinfile:
    path: "/etc/fstab"
    regexp: " swap "
    state: "absent"

- name: Limit journald memory to 64M
  lineinfile:
    path: /etc/systemd/journald.conf
    regexp: RuntimeMaxUse=
    line: RuntimeMaxUse=64M
    insertbefore: RuntimeKeepFree
  notify: Restart journald service

- name: Enable generic services
  systemd:
    name: "{{ item }}"
    enabled: true
    state: started
  ignore_errors: true
  with_items:
    - "{{ generic_services }}"
    - "{{ distro_services|default() }}"

- name: Disable generic services
  systemd:
    name: "{{ item }}"
    enabled: false
    state: stopped
  ignore_errors: true
  with_items:
    - "{{ generic_services_stopped }}"

- name: Include distro-specific tasks
  include_tasks: "subtasks/{{ ansible_os_family|lower }}.yml"

- name: Tune rc.local
  include_tasks: "rc-local.yml"
  when:
    - sp_vm is defined and
      not sp_vm | bool

- name: Flush handlers
  meta: flush_handlers
