---
- name: Running storpool_hugepages
  command: /usr/sbin/storpool_hugepages
  register: create_storpool_hugepages_result
  failed_when: create_storpool_hugepages_result.rc != 0

- name: Enable Storpool services
  command: "{{ sp_ctl }} enable --batch"
  changed_when: false

- name: Start Storpool services
  command: "{{ sp_ctl }} start --batch"
  changed_when: false
  when:
    - start_services is not defined or
      start_services | bool
