---
- name: Checking if the host is defined in storpool.conf
  ansible.builtin.assert:
    that:
      - host_sp_ourid != ""
    fail_msg: "Cannot determine SP_OURID from configuration"
  vars:
    host_sp_ourid: lookup('ansible.builtin.ini', 'SP_OURID', section=ansible_hostname, file=sp_configuration_path)

- name: Checking if the playbook is executed on the bastion host
  ansible.builtin.set_fact:
    is_bastion_host: "{{ hostvars['localhost'].ansible_hostname == 'poli' | bool }}"

- name: Executing pre-installation tasks
  import_tasks: "pre_install.yml"

- name: Executing installation tasks
  import_tasks: "install_storpool.yml"

- name: Executing post-installation tasks (Install Storpool)
  import_tasks: "post_install.yml"
