---
- name: Restarting rsyslog
  become: true
  ansible.builtin.systemd:
    name: rsyslog
    state: restarted
    enabled: yes

- name: Reloading sysctl entries
  become: true
  ansible.builtin.command: /sbin/sysctl --system
  changed_when: false

- name: Enabling IOMMU in GRUB config
  become: true
  command: /usr/lib/storpool/enable_grub_iommu
  when:
    - not sp_vm | bool
    - sp_run_enable_grub_iommu | bool
  changed_when: false

- name: Include distro-specific tasks
  include_tasks: "post_install_{{ ansible_os_family | lower }}.yml"

- name: Test Memory - check on async task
  become: true
  async_status:
    jid: "{{ memory_test_sleeper.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 200
  delay: 30
  when:
    - not sp_vm | bool
    - memory_test_sleeper is defined
    - memory_test_sleeper.ansible_job_id is defined
