---
- name: Restarting rsyslog
  become: true
  ansible.builtin.systemd:
    name: rsyslog
    state: restarted
    enabled: yes

- name: Reloading sysctl entries
  become: true
  ansible.builtin.command: /sbin/sysctl --system
  changed_when: false

- name: Enabling IOMMU in GRUB config
  become: true
  command: /usr/lib/storpool/enable_grub_iommu
  when:
    - not sp_vm | bool
    - sp_run_enable_grub_iommu | bool
  notify: Update GRUB configuration

- name: Increasing crashkernel size (Debian/Ubuntu)
  become: true
  ansible.builtin.lineinfile:
    path: /etc/default/grub.d/kdump-tools.cfg
    create: yes
    line: GRUB_CMDLINE_LINUX_DEFAULT="$GRUB_CMDLINE_LINUX_DEFAULT crashkernel=512M"
  notify: Update GRUB configuration
  when:
    - ansible_os_family == "Debian"

- name: Running patchkdumptools (Debian/Ubuntu)
  become: true
  command: "{{ sp_patchkdumptools_path }}"
  notify: Update GRUB configuration

- name: Waiting for memory tests to complete
  become: true
  async_status:
    jid: "{{ memory_test_sleeper.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 200
  delay: 30
  when:
    - not sp_vm | bool
    - memory_test_sleeper is defined
    - memory_test_sleeper.ansible_job_id is defined
