---
- name: Restarting rsyslog
  become: true
  ansible.builtin.systemd:
    name: rsyslog
    state: restarted
    enabled: yes

- name: Reloading sysctl entries
  become: true
  ansible.builtin.command: /sbin/sysctl --system
  changed_when: false

- name: Enabling IOMMU in GRUB config
  become: true
  command: /usr/lib/storpool/enable_grub_iommu --no-change-exit-status 254
  register: enable_grub_iommu_result
  when:
    - not sp_vm | bool
    - sp_run_enable_grub_iommu | bool
  changed_when: enable_grub_iommu_result.rc == 0
  failed_when:
    - enable_grub_iommu_result.rc != 0
    - enable_grub_iommu_result.rc != 254
  notify: Update GRUB configuration

- name: Increasing crashkernel size (Debian/Ubuntu)
  become: true
  ansible.builtin.lineinfile:
    path: /etc/default/grub.d/kdump-tools.cfg
    create: yes
    line: GRUB_CMDLINE_LINUX_DEFAULT="$GRUB_CMDLINE_LINUX_DEFAULT crashkernel=512M"
  notify: Update GRUB configuration
  when:
    - ansible_os_family == "Debian"

- name: Running patchkdumptools on Debian-based OS
  become: true
  command: /usr/lib/storpool/patchkdumptools --no-change-exit-status 254
  register: patch_kdump_tools_result
  changed_when: patch_kdump_tools_result.rc == 0
  failed_when:
    - patch_kdump_tools_result.rc != 0
    - patch_kdump_tools_result.rc != 254
  notify: Update GRUB configuration
  when:
    - ansible_os_family == "Debian"

- name: Waiting for memory tests to complete
  become: true
  async_status:
    jid: "{{ memory_test_sleeper.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 200
  delay: 30
  when:
    - not sp_vm | bool
    - memory_test_sleeper is defined
    - memory_test_sleeper.ansible_job_id is defined
