---
- name: Copying storpool.conf
  become: true
  copy:
    src: "{{ sp_configuration_path }}"
    dest: /etc/
  tags:
    - copy-storpool-conf

- name: Creating directories
  import_tasks: "create_directories.yml"

- name: Install support tools
  import_tasks: "subtasks/support_tools.yml"
  when:
    - sp_poli is defined
    - sp_poli | bool
  tags:
    - install-support-tools

- name: Test memory
  import_tasks: "test_memory.yml"
  when:
    - not sp_vm | bool
  tags:
    - test-memory
