---
- name: Include distro-specific variables
  include_vars: "{{ ansible_os_family|lower }}.yml"
  tags: ['dependencies']

- name: Include distro-specific tasks
  include_tasks: "subtasks/{{ ansible_os_family|lower }}.yml"
  tags: ['dependencies']

- name: Install dependencies
  become: true
  become_user: root
  package:
    name: "{{ dependencies }}"
    state: latest
    update_cache: "{{ (ansible_pkg_mgr=='apt') | ternary('yes', omit) }}"
    cache_valid_time: "{{ (ansible_pkg_mgr=='apt') | ternary(cache_timeout, omit) }}"
  vars:
    dependencies: "{{ generic_deps + (distro_deps|default()) }}" 
  tags: ['dependencies']
