---
- name: Gather localhost-related facts 
  include_tasks: variables-localhost.yml

- name: Gather common facts 
  include_tasks: variables-common.yml

- name: Check variables 
  include_tasks: check-variables.yml

- name: Check requirements
  include_tasks: check-requirements.yml

- name: Generate summary message 
  set_fact:
    sp_summary_msg: # do not use tabs below - the output gets ugly
      - "OS update:        {{ sp_update_system }}"
      - "Net config:       {{ sp_configure_network }} ({{ '' if sp_overwrite_iface_conf and sp_configure_network else 'do not ' }}overwrite existing)"
      - "Network Manager:  {{ 'disable' if sp_disable_nm else 'leave as is' }}"
      - "Firewall:         {{ 'disable' if sp_disable_fw else 'adjust' }}"
      - "SELinux:          {{ sp_selinux }}"
      - "VM Node:          {{ sp_vm }} ({{ 'Guessed' if sp_vm_guessed is defined else 'Defined' }}, Product Name: {{ ansible_product_name }})"
      - "New Cluster:      {{ sp_new_cluster }}{{' (initial disk node)' if sp_new_cluster and sp_init_node == ansible_fqdn else ''}}"
      - "SP release:       {{ sp_release }}"
      - "Release Source:   {{ sp_release_file }}"
      - "storpool.conf:    {{ sp_config }}"
      - "node roles:       {{ sp_node_roles }}"
      - "install.sh:       {{ sp_install_services }}"
      - "Drives to init:   {{ sp_drive_list | sort | join(', ') if sp_roles.server else 'none' }}"
      - "Server Instances: {{ sp_server_instances }}"
      - "storpool_cg conf: {{ sp_cg_conf_extra|default('default') }}"
  when: sp_summary_wait

- name: Preview configuration summary 
  debug: var=sp_summary_msg
  when: sp_summary_wait

- name: Confirm configuration 
  pause:
    prompt: "\nPlease Review\n\nPress Enter to begin deployment\nor Ctrl-C,A to abort"
  when: sp_summary_wait
