---
- name: Include common facts gathering tasks (Prepare Deployment)
  import_tasks: variables-common.yml

- name: Validate deployment variables (Prepare Deployment)
  import_tasks: check-variables.yml

- name: Preview deployment summary (Prepare Deployment)
  include_tasks: summary.yml
  when:
    - sp_summary_wait
