---
- name: Configure Network
  import_tasks: "subtasks/configure_network.yml"
  when:
  - sp_configure_network is defined and
    sp_configure_network|bool
  tags: ['setup-network']

- name: Validate Network
  import_tasks: "subtasks/network_validation.yml"
  tags: ['setup-network']

- name: Make bond adjustments
  import_tasks: "subtasks/bond_adjustments.yml"
  when:
  - sp_configure_network is defined and
    sp_configure_network|bool
  tags: ['setup-network']
