---
- name: Install (StorPool Support Tools)
  delegate_to: localhost
  run_once: false
  become: no
  command:
    chdir: "{{ sp_custdir }}/{{ sp_cluster }}"
    cmd: /usr/local/bin/installtools {{ inventory_hostname }}
  changed_when: false
  when: sp_cluster is defined
  tags: ['install', 'install-support_tools']

- name: Check if mlc exists (StorPool Support Tools)
  stat:
    path: "{{ sp_toolsdir }}/mlc/mlc"
  register: mlc_present
  when: 
    - sp_vm is defined and
      not sp_vm|bool
  tags: ['install', 'install-support_tools']

- name: Perform mlc test (StorPool Support Tools)
  shell: >
    set -o pipefail && \
      [[ ! -d "/tmp/mlc/" ]] && mkdir -p /tmp/mlc/; \
      [[ ! -f "/tmp/mlc/mlc.output" ]] && {{ sp_toolsdir }}/mlc/mlc > /tmp/mlc/mlc.output || /bin/true
  changed_when: false
  when:
    - sp_vm is defined and
      mlc_present.stat is defined and
      not sp_vm|bool and 
      mlc_present.stat.exists|bool
  tags: ['install', 'install-support_tools']

- name: Collect inventory (StorPool Support Tools)
  delegate_to: localhost
  run_once: false
  become: no
  command:
    chdir: "{{ sp_custdir }}/{{ sp_cluster }}"
    cmd: /usr/local/bin/collect_inventory "{{ inventory_hostname }}"
  changed_when: false
  tags: ['install', 'install-support_tools']

