---
## Distribution packages to install (Redhat/CentOS-specific)
distro_deps:
  - cpupowerutils
  - libcgroup-tools
  - lz4
  - mcelog
  - perf
  - perl-core
  - smartmontools
  - tuned
  - vim-enhanced
