---
- name: Start StorPool installation
  hosts: storpool
  gather_facts: false
  become: true

  tasks:
    - name: Install StorPool
      import_role:
        name: 3_install-storpool

  tags:
    - install
