---
- name: Setup Network
  hosts: storpool
  gather_facts: false
  become: true

  tasks:
    - name: Configure StorPool network
      import_role:
        name: 4_setup-network

  tags:
    - setup-network
