---
- name: Setup Drives
  hosts: storpool
  gather_facts: false
  become: true

  pre_tasks:
    - name: Prepare Variables 
      include_role:
        name: 5_setup-drives
        tasks_from: prerequisites 

  tasks:
    - name: Configure StorPool drives
      import_role:
        name: 5_setup-drives

  tags:
    - setup-drives
