---
- name: Run common tests
  hosts: storpool
  gather_facts: false
  serial: 1
  become: true

  tasks:
    - name: Test configuration
      import_role:
        name: 8_tests

  tags:
    - never
    - tests
