---
- name: Reboot Hosts
  hosts: storpool
  gather_facts: false
  serial: 1
  become: true

  tasks:
    - name: Reboot host
      import_role:
        name: 0_common
        tasks_from: reboot_hosts

  tags:
    - never
    - reboot
